In [32]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv('bharatkart_sales_dataset.csv')

In [34]:
df.head()

,company_name,order_id,order_date,customer_id,customer_name,city,state,product_category,product_name,order_value,discount_percent,payment_mode,delivery_days,rating
0,BharatKart Retail Pvt Ltd,5271,2023-01-01 00:00:00,2516,Vikas Gupta,Mumbai,TS,Home,Mobile,88743.0,20.0,NaN,13,3.0
1,BharatKart Retail Pvt Ltd,2220,2023-01-01 01:00:00,5658,Priya Singh,NaN,TS,Fashion,Sofa,23597.0,10.0,Card,14,1.0
2,BharatKart Retail Pvt Ltd,1537,2023-01-01 02:00:00,881,Rahul Verma,Delhi,NaN,Grocery,NaN,48598.0,30.0,NaN,6,4.0
3,BharatKart Retail Pvt Ltd,3550,2023-01-01 03:00:00,2006,Vikas Gupta,Pune,DL,Home,Shirt,72738.0,10.0,UPI,7,3.0
4,BharatKart Retail Pvt Ltd,6699,2023-01-01 04:00:00,3769,Priya Singh,Bangalore,KA,Home,Sofa,19335.0,20.0,UPI,6,5.0

In [35]:
df.columns

Index(['company_name', 'order_id', 'order_date', 'customer_id',
       'customer_name', 'city', 'state', 'product_category', 'product_name',
       'order_value', 'discount_percent', 'payment_mode', 'delivery_days',
       'rating'],
      dtype='object')

In [36]:
df=df.drop('company_name',axis=1)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26200 entries, 0 to 26199
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          26200 non-null  int64
 1   order_date        26200 non-null  object
 2   customer_id       26200 non-null  int64
 3   customer_name     22044 non-null  object
 4   city              22638 non-null  object
 5   state             21937 non-null  object
 6   product_category  21046 non-null  object
 7   product_name      21865 non-null  object
 8   order_value       24628 non-null  float64
 9   discount_percent  21880 non-null  float64
 10  payment_mode      19626 non-null  object
 11  delivery_days     26200 non-null  int64
 12  rating            21909 non-null  float64
dtypes: float64(3), int64(3), object(7)
memory usage: 2.6+ MB

In [38]:
df.describe()

,order_id,customer_id,order_value,discount_percent,delivery_days,rating
count,26200.000000,26200.000000,24628.000000,21880.000000,26200.000000,21909.000000
mean,4994.988282,3042.012863,60131.251990,13.045247,7.509618,3.003332
std,2298.202551,1702.129945,34440.033326,10.763498,4.025092,1.419638
min,1000.000000,100.000000,100.000000,0.000000,1.000000,1.000000
25%,3009.000000,1564.000000,30527.750000,5.000000,4.000000,2.000000
50%,4999.000000,3021.500000,60508.000000,10.000000,8.000000,3.000000
75%,6962.000000,4527.000000,89721.500000,20.000000,11.000000,4.000000
max,8999.000000,5999.000000,119998.000000,30.000000,14.000000,5.000000

In [39]:
df.isnull().sum()  # to check missing values in data

order_id               0
order_date             0
customer_id            0
customer_name       4156
city                3562
state               4263
product_category    5154
product_name        4335
order_value         1572
discount_percent    4320
payment_mode        6574
delivery_days          0
rating              4291
dtype: int64

In [40]:
df['city'] = df['city'].fillna('Unknown') # to fill missing values as Unknown for missing city
df['state'] = df['state'].fillna('NA')  # to fill missing states as NA
df['product_category'] = df['product_category'].fillna('Unknown') # to fill missing product_category as Unknown
df['product_name'] = df['product_name'].fillna('Unknown')

In [41]:
df['city'].unique()

array(['Mumbai', 'Unknown', 'Delhi', 'Pune', 'Bangalore', 'unknown',
       'Hyderabad', 'Chennai'], dtype=object)

In [42]:
df['city'] = df['city'].replace('unknown','Unknown')

In [43]:
df['city'].unique()

array(['Mumbai', 'Unknown', 'Delhi', 'Pune', 'Bangalore', 'Hyderabad',
       'Chennai'], dtype=object)

In [44]:
df['state'].unique()

array(['TS', 'NA', 'DL', 'KA', 'TN', 'MH'], dtype=object)

In [45]:
df['discount_percent'] = df['discount_percent'].fillna(0)

In [46]:
df["rating"] = df["rating"].fillna(df.groupby('product_category')['rating'].transform('median')) # To fill missing values by respective product categories

In [47]:
df['payment_mode'] = df['payment_mode'].fillna('Unkonwn')

In [48]:
df.isnull().sum()

order_id               0
order_date             0
customer_id            0
customer_name       4156
city                   0
state                  0
product_category       0
product_name           0
order_value         1572
discount_percent       0
payment_mode           0
delivery_days          0
rating                 0
dtype: int64

In [49]:
df["customer_name"] = df["customer_name"].fillna('Unkonwn')

In [50]:
df["customer_name"] = df["customer_name"].str.title()

In [51]:
df['order_value'] = df['order_value'].fillna(df.groupby('product_category')['order_value'].transform('median'))

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26200 entries, 0 to 26199
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          26200 non-null  int64
 1   order_date        26200 non-null  object
 2   customer_id       26200 non-null  int64
 3   customer_name     26200 non-null  object
 4   city              26200 non-null  object
 5   state             26200 non-null  object
 6   product_category  26200 non-null  object
 7   product_name      26200 non-null  object
 8   order_value       26200 non-null  float64
 9   discount_percent  26200 non-null  float64
 10  payment_mode      26200 non-null  object
 11  delivery_days     26200 non-null  int64
 12  rating            26200 non-null  float64
dtypes: float64(3), int64(3), object(7)
memory usage: 2.6+ MB

In [53]:
df['rating'] = df['rating'].astype(int)

In [56]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [58]:
df['month'] = df['order_date'].dt.month
df['year'] = df['order_date'].dt.year

In [60]:
df.to_csv("bharatkart_cleaned.csv", index = False)